from __future__ import annotations

import io
import json
from datetime import datetime, timezone

import numpy as np
import pandas as pd


def to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8-sig")


def to_excel_bytes(result: dict, diagnostics: pd.DataFrame | None = None) -> bytes:
    """Ridership-only drill-down workbook generated by the Streamlit app."""
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        pd.DataFrame([result["summary"]]).to_excel(writer, sheet_name="Summary", index=False)
        result["findings"].to_excel(writer, sheet_name="Findings", index=False)
        inf = result["rule_inference"]
        if not inf.rules.empty:
            inf.rules.to_excel(writer, sheet_name="Inferred_Rules", index=False)
        if not inf.route_fit.empty:
            inf.route_fit.to_excel(writer, sheet_name="Legacy_Ridership_Fit", index=False)

        drill = result.get("drilldowns", {})
        sheet_map = [
            ("day_comparison", "By_Day"),
            ("day_identifier", "Day_Key_TTP"),
            ("route_comparison_by_day", "Day_Route"),
            ("run_comparison_by_day", "Day_Run"),
            ("bus_comparison_by_day", "Day_Bus"),
            ("route_run_bus_by_day", "Day_Route_Run_Bus"),
            ("equal_opposite_movements", "Equal_Opposite_Moves"),
            ("transaction_matches", "Transaction_Matches"),
        ]
        for key, sheet in sheet_map:
            df = drill.get(key, pd.DataFrame())
            if df is not None and not df.empty:
                df.to_excel(writer, sheet_name=sheet, index=False)

        if not result.get("route_reassignments", pd.DataFrame()).empty:
            result["route_reassignments"].to_excel(writer, sheet_name="Overall_Data_Edits", index=False)
        if diagnostics is not None and not diagnostics.empty:
            diagnostics.to_excel(writer, sheet_name="Diagnostics", index=False)

        for ws in writer.book.worksheets:
            ws.freeze_panes = "A2"
            ws.auto_filter.ref = ws.dimensions
            for col_cells in ws.columns:
                max_len = 0
                for cell in list(col_cells)[:250]:
                    value = "" if cell.value is None else str(cell.value)
                    max_len = max(max_len, min(len(value), 60))
                ws.column_dimensions[col_cells[0].column_letter].width = max(10, min(max_len + 2, 45))
    return output.getvalue()


def _json_scalar(value):
    if value is None:
        return None
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating, float)):
        if pd.isna(value) or np.isinf(value):
            return None
        return float(value)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    if pd.isna(value):
        return None
    return value


def _records(df: pd.DataFrame, limit: int | None = None) -> list[dict]:
    if df is None or df.empty:
        return []
    work = df.copy()
    if limit is not None:
        work = work.head(limit)
    return [{str(k): _json_scalar(v) for k, v in row.items()} for row in work.to_dict(orient="records")]


def build_ai_evidence_package(result: dict, diagnostics: pd.DataFrame | None = None) -> dict:
    findings = result["findings"].copy()
    nonmatches = findings
    if not findings.empty:
        nonmatches = findings[(findings["Status"] != "Match") | (findings["Severity"] != "Info")].copy()
        nonmatches["_abs"] = pd.to_numeric(nonmatches["Difference"], errors="coerce").abs().fillna(0)
        nonmatches = nonmatches.sort_values("_abs", ascending=False).drop(columns="_abs")

    inf = result["rule_inference"]
    drill = result.get("drilldowns", {})
    return {
        "package_type": "Genfare ridership reconciliation drill-down evidence",
        "package_version": "4.6",
        "scope": "RIDERSHIP ONLY — do not analyze or infer revenue from this package.",
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "analysis_instructions": [
            "Use the deterministic calculations as the source of truth for arithmetic.",
            "Follow the drill-down order: overall raw difference, by day, systemwide Key/TTP counts by day, route/run/bus localization, then transaction matches.",
            "Separate ridership-rule/configuration differences from event-count differences.",
            "Treat aggregate balancing offsets only as clues. They are not proof that the same riders moved, and they must never be used to pair different buses as one reassignment.",
            "Use exact timestamp + bus + category transaction-match evidence to distinguish confirmed assignment differences from truly missing or extra rider events.",
            "Count issues affect systemwide ridership. Assignment-only differences do not affect systemwide ridership.",
            "Pay attention to Legacy internal key-ridership display inconsistencies where the detailed display says 0 but overall/route totals prove the category contributes riders.",
            "Do not invent causes. Mark unresolved items and state the next report/configuration check that would resolve them.",
            "Evidence confidence percentages are deterministic match-strength scores, not statistical probabilities.",
        ],
        "privacy_note": "The package excludes card IDs, Track 2, ticket/sequence IDs, and other unnecessary customer identifiers.",
        "summary": {k: _json_scalar(v) for k, v in result["summary"].items()},
        "diagnostics": _records(diagnostics if diagnostics is not None else pd.DataFrame()),
        "rule_inference": {
            "confidence": int(inf.confidence),
            "exact_fit": bool(inf.exact_fit),
            "source": inf.source,
            "warnings": list(inf.warnings or []),
            "rules": _records(inf.rules),
            "legacy_route_fit": _records(inf.route_fit),
        },
        "drilldown": {
            "by_day": _records(drill.get("day_comparison", pd.DataFrame())),
            "day_key_ttp": _records(drill.get("day_identifier", pd.DataFrame()), limit=1000),
            "route_differences_by_day": _records(drill.get("route_comparison_by_day", pd.DataFrame()), limit=1000),
            "run_differences_by_day": _records(drill.get("run_comparison_by_day", pd.DataFrame()), limit=1000),
            "bus_differences_by_day": _records(drill.get("bus_comparison_by_day", pd.DataFrame()), limit=1000),
            "equal_and_opposite_movements": _records(drill.get("equal_opposite_movements", pd.DataFrame()), limit=1000),
            "transaction_matches": _records(drill.get("transaction_matches", pd.DataFrame()), limit=1000),
            "notes": list(drill.get("notes", [])),
        },
        "largest_nonmatching_findings": _records(nonmatches, limit=300),
        "truncation_note": "Large detailed tables are capped in the AI JSON for usability. The Excel export retains the complete deterministic drill-down tables.",
    }


def to_ai_json_bytes(result: dict, diagnostics: pd.DataFrame | None = None) -> bytes:
    return json.dumps(build_ai_evidence_package(result, diagnostics), indent=2, ensure_ascii=False, allow_nan=False).encode("utf-8")


def to_ai_prompt_bytes() -> bytes:
    text = """# Genfare Ridership Reconciliation V4.6 — AI Review Prompt

I am attaching `ridership_ai_evidence_v4_6.json`, generated by a deterministic Genfare ridership reconciliation tool.

Analyze RIDERSHIP ONLY. Do not analyze revenue.

Follow the evidence in this order:
1. Overall raw Legacy vs GFL ridership difference.
2. Which day(s) contain the discrepancy.
3. Key/TTP/Preset event-count and rider-contribution differences on those days.
4. Where those category differences land across route, run, and bus.
5. Aggregate balancing offsets as unconfirmed clues only.
6. Exact transaction-match evidence that separates missing/extra riders from assignment-only differences.

For every important discrepancy, state:
- what differs,
- likely cause,
- qualitative confidence (High / Medium / Low),
- the specific evidence supporting that conclusion,
- whether it affects systemwide ridership or only allocation,
- the next check to perform if unresolved.

Do not assume every route/run/bus difference means a missing rider. Aggregate offsets are not confirmation. Only call a rider missing/extra when the exact date/time/bus/category transaction matcher shows a count difference. If the same timestamp/bus/category exists in both systems but route/run/trip differs, identify it as an assignment-only difference and state that it does not change systemwide ridership.

Return:
- Executive summary
- Overall reconciliation
- Problem days
- Fare-category findings
- Route/run/bus findings
- Transaction-match findings
- Remaining unresolved issues
- Recommended next checks
"""
    return text.encode("utf-8")
